package com.hrflow.platform.auth;
import com.hrflow.platform.common.ApiModels.*; import com.hrflow.platform.email.EmailService; import com.hrflow.platform.exception.ApiException; import com.hrflow.platform.security.JwtService; import com.hrflow.platform.user.*; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.Base64;
@Service @RequiredArgsConstructor
public class AuthService { private final UserRepository users; private final EmailVerificationTokenRepository verifies; private final PasswordResetTokenRepository resets; private final PasswordEncoder passwords; private final JwtService jwt; private final EmailService email; private final SecureRandom random=new SecureRandom(); @Value("${hrflow.tokens.verification-ttl:PT24H}")Duration verifyTtl; @Value("${hrflow.tokens.reset-ttl:PT30M}")Duration resetTtl;
 @Transactional public Message register(Register in){String address=normalize(in.email());if(users.existsByEmailIgnoreCase(address))throw new ApiException(HttpStatus.CONFLICT,"EMAIL_ALREADY_USED","Cette adresse est déjà utilisée");User u=new User();u.setEmail(address);u.setPasswordHash(passwords.encode(in.password()));users.save(u);sendVerification(u);return new Message("Inscription réussie. Consultez votre email pour activer le compte.");}
 @Transactional(readOnly=true) public TokenResponse login(Login in){User u=users.findByEmailIgnoreCase(normalize(in.email())).orElseThrow(this::badCredentials);if(!u.isEnabled()||!passwords.matches(in.password(),u.getPasswordHash()))throw badCredentials();if(!u.isEmailVerified())throw new ApiException(HttpStatus.FORBIDDEN,"EMAIL_NOT_VERIFIED","Adresse email non vérifiée");return new TokenResponse(jwt.generate(u),"Bearer",jwt.expiresSeconds());}
 @Transactional public Message verify(String raw){EmailVerificationToken t=verifies.findByTokenHash(hash(raw)).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_TOKEN","Token invalide ou expiré"));if(t.getUsedAt()!=null||t.getExpiresAt().isBefore(Instant.now()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_TOKEN","Token invalide ou expiré");t.setUsedAt(Instant.now());t.getUser().setEmailVerified(true);return new Message("Adresse email vérifiée");}
 @Transactional public Message resend(EmailInput in){users.findByEmailIgnoreCase(normalize(in.email())).filter(u->!u.isEmailVerified()&&u.isEnabled()).ifPresent(this::sendVerification);return generic();}
 @Transactional public Message forgot(EmailInput in){users.findByEmailIgnoreCase(normalize(in.email())).filter(User::isEnabled).ifPresent(this::sendReset);return generic();}
 @Transactional public Message reset(ResetPassword in){PasswordResetToken t=resets.findByTokenHash(hash(in.token())).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_TOKEN","Token invalide ou expiré"));if(t.getUsedAt()!=null||t.getExpiresAt().isBefore(Instant.now()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_TOKEN","Token invalide ou expiré");t.setUsedAt(Instant.now());t.getUser().setPasswordHash(passwords.encode(in.newPassword()));resets.invalidate(t.getUser().getId(),Instant.now());return new Message("Mot de passe réinitialisé");}
 @Transactional(readOnly=true) public UserView me(String email){return view(users.findByEmailIgnoreCase(email).orElseThrow(()->ApiException.notFound("Utilisateur introuvable")));}
 private void sendVerification(User u){Instant now=Instant.now();verifies.invalidate(u.getId(),now);String raw=token();EmailVerificationToken t=new EmailVerificationToken();t.setUser(u);t.setTokenHash(hash(raw));t.setExpiresAt(now.plus(verifyTtl));verifies.save(t);email.verification(u.getEmail(),raw);}
 private void sendReset(User u){Instant now=Instant.now();resets.invalidate(u.getId(),now);String raw=token();PasswordResetToken t=new PasswordResetToken();t.setUser(u);t.setTokenHash(hash(raw));t.setExpiresAt(now.plus(resetTtl));resets.save(t);email.reset(u.getEmail(),raw);}
 private String token(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}} private String normalize(String e){return e.trim().toLowerCase(java.util.Locale.ROOT);} private ApiException badCredentials(){return new ApiException(HttpStatus.UNAUTHORIZED,"BAD_CREDENTIALS","Identifiants invalides");} private Message generic(){return new Message("Si le compte existe, un email a été envoyé.");} public static UserView view(User u){return new UserView(u.getId(),u.getEmail(),u.getRole(),u.isEnabled(),u.isEmailVerified(),u.getCreatedAt());}
}
