package com.hrflow.platform.recruitment;
import com.hrflow.platform.exception.ApiException; import com.hrflow.platform.recruitment.RecruitmentDtos.CvView;
import io.micrometer.core.instrument.MeterRegistry; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import java.io.*; import java.nio.file.*; import java.security.*; import java.time.Instant; import java.util.HexFormat; import java.util.UUID;
@Service @RequiredArgsConstructor public class CvStorageService {
 private final CvDocumentRepository documents; private final CandidateRepository candidates; private final MeterRegistry metrics;
 @Value("${hrflow.cv.storage-directory:/tmp/hrflow-cv}") String configuredRoot;
 @Value("${hrflow.cv.max-size:5242880}") long maxSize;
 @Transactional public CvView store(Long candidateId,MultipartFile file){try{Candidate c=candidates.findById(candidateId).orElseThrow(()->ApiException.notFound("Candidat introuvable"));if(file.isEmpty()||file.getSize()>maxSize)throw ApiException.conflict("CV vide ou trop volumineux");byte[] bytes=file.getBytes();if(bytes.length<5||bytes[0]!='%'||bytes[1]!='P'||bytes[2]!='D'||bytes[3]!='F'||bytes[4]!='-')throw ApiException.conflict("Seuls les fichiers PDF valides sont acceptés");Path root=Path.of(configuredRoot).toAbsolutePath().normalize();Files.createDirectories(root);String stored=UUID.randomUUID()+".pdf";Path target=root.resolve(stored).normalize();if(!target.startsWith(root))throw ApiException.conflict("Chemin de stockage invalide");documents.findByCandidateIdAndDeletedAtIsNull(candidateId).ifPresent(old->{old.setDeletedAt(Instant.now());safeDelete(old.getStoragePath(),root);});Files.write(target,bytes,StandardOpenOption.CREATE_NEW);CvDocument d=new CvDocument();d.setCandidate(c);d.setOriginalFilename(safeName(file.getOriginalFilename()));d.setStoredFilename(stored);d.setContentType("application/pdf");d.setSize(bytes.length);d.setStoragePath(target.toString());d.setChecksum(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes)));return view(documents.save(d));}catch(ApiException e){metrics.counter("hrflow.recruitment.cv.upload.errors").increment();throw e;}catch(IOException|NoSuchAlgorithmException e){metrics.counter("hrflow.recruitment.cv.upload.errors").increment();throw new ApiException(org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR,"CV_STORAGE_ERROR","Impossible de stocker le CV");}}
 @Transactional(readOnly=true) public Download download(Long candidateId){CvDocument d=active(candidateId);Path root=Path.of(configuredRoot).toAbsolutePath().normalize();Path p=Path.of(d.getStoragePath()).toAbsolutePath().normalize();if(!p.startsWith(root)||!Files.isRegularFile(p))throw ApiException.notFound("CV introuvable");return new Download(view(d),new FileSystemResource(p));}
 @Transactional public void delete(Long candidateId){CvDocument d=active(candidateId);d.setDeletedAt(Instant.now());safeDelete(d.getStoragePath(),Path.of(configuredRoot).toAbsolutePath().normalize());}
 @Transactional(readOnly=true) public CvView metadata(Long candidateId){return view(active(candidateId));}
 private CvDocument active(Long id){return documents.findByCandidateIdAndDeletedAtIsNull(id).orElseThrow(()->ApiException.notFound("CV introuvable"));}
 private static String safeName(String n){if(n==null||n.isBlank())return "cv.pdf";String x=Path.of(n).getFileName().toString().replaceAll("[\\r\\n]","_");return x.length()>255?x.substring(x.length()-255):x;}
 private static void safeDelete(String value,Path root){try{Path p=Path.of(value).toAbsolutePath().normalize();if(p.startsWith(root))Files.deleteIfExists(p);}catch(IOException ignored){}}
 private CvView view(CvDocument d){return new CvView(d.getId(),d.getCandidate().getId(),d.getOriginalFilename(),d.getContentType(),d.getSize(),d.getChecksum(),d.getUploadedAt());}
 public record Download(CvView metadata,Resource resource){}
}
