package com.hrflow.platform.recruitment;

import com.hrflow.platform.department.*; import com.hrflow.platform.email.EmailService; import com.hrflow.platform.employee.*;
import com.hrflow.platform.exception.ApiException; import com.hrflow.platform.recruitment.RecruitmentDtos.*; import com.hrflow.platform.user.*;
import io.micrometer.core.instrument.MeterRegistry; import jakarta.persistence.criteria.Predicate; import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.Authentication; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;

@Service @RequiredArgsConstructor
public class RecruitmentService {
 private final JobOfferRepository offers; private final CandidateRepository candidates; private final ApplicationRepository applications;
 private final InterviewRepository interviews; private final EvaluationRepository evaluations; private final RecruitmentAuditRepository auditRepo;
 private final DepartmentRepository departments; private final EmployeeRepository employees; private final UserRepository users;
 private final PasswordEncoder encoder; private final EmailService email; private final MeterRegistry metrics;
 private static final Map<ApplicationStage,Set<ApplicationStage>> TRANSITIONS=Map.of(
  ApplicationStage.APPLIED,Set.of(ApplicationStage.SCREENING,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN),
  ApplicationStage.SCREENING,Set.of(ApplicationStage.INTERVIEW,ApplicationStage.TECHNICAL_TEST,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN),
  ApplicationStage.INTERVIEW,Set.of(ApplicationStage.TECHNICAL_TEST,ApplicationStage.HR_INTERVIEW,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN),
  ApplicationStage.TECHNICAL_TEST,Set.of(ApplicationStage.HR_INTERVIEW,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN),
  ApplicationStage.HR_INTERVIEW,Set.of(ApplicationStage.OFFER,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN),
  ApplicationStage.OFFER,Set.of(ApplicationStage.HIRED,ApplicationStage.REJECTED,ApplicationStage.WITHDRAWN));

 @Transactional public JobOfferView createOffer(JobOfferInput i,String actor){if(offers.existsByReferenceIgnoreCase(i.reference()))throw ApiException.conflict("Cette référence existe déjà");JobOffer o=new JobOffer();apply(o,i);o=offers.save(o);audit("JOB_OFFER",o.getId(),"CREATED",actor,null);return offerView(o);}
 @Transactional public JobOfferView updateOffer(Long id,JobOfferInput i,String actor){JobOffer o=offer(id);if(o.getStatus()!=JobOfferStatus.DRAFT)throw ApiException.conflict("Seule une offre brouillon peut être modifiée");if(offers.existsByReferenceIgnoreCaseAndIdNot(i.reference(),id))throw ApiException.conflict("Cette référence existe déjà");apply(o,i);audit("JOB_OFFER",id,"UPDATED",actor,null);return offerView(o);}
 @Transactional public JobOfferView publish(Long id,String actor){JobOffer o=offer(id);if(o.getStatus()!=JobOfferStatus.DRAFT)throw ApiException.conflict("Seule une offre brouillon peut être publiée");if(o.getClosingDate()!=null&&o.getClosingDate().isBefore(LocalDate.now()))throw ApiException.conflict("La date de clôture est passée");o.setStatus(JobOfferStatus.PUBLISHED);o.setPublishedAt(Instant.now());audit("JOB_OFFER",id,"PUBLISHED",actor,null);return offerView(o);}
 @Transactional public JobOfferView close(Long id,String actor){JobOffer o=offer(id);if(o.getStatus()!=JobOfferStatus.PUBLISHED)throw ApiException.conflict("Seule une offre publiée peut être clôturée");o.setStatus(JobOfferStatus.CLOSED);audit("JOB_OFFER",id,"CLOSED",actor,null);return offerView(o);}
 @Transactional public JobOfferView cancel(Long id,String actor){JobOffer o=offer(id);if(o.getStatus()==JobOfferStatus.CLOSED||o.getStatus()==JobOfferStatus.CANCELLED)throw ApiException.conflict("Offre déjà terminée");o.setStatus(JobOfferStatus.CANCELLED);audit("JOB_OFFER",id,"CANCELLED",actor,null);return offerView(o);}
 @Transactional(readOnly=true) public Page<JobOfferView> listOffers(String q,JobOfferStatus status,Long departmentId,Pageable p,Authentication a,boolean publicOnly){Specification<JobOffer>s=(r,c,b)->{List<Predicate>x=new ArrayList<>();if(publicOnly)x.add(b.equal(r.get("status"),JobOfferStatus.PUBLISHED));else if(status!=null)x.add(b.equal(r.get("status"),status));if(q!=null&&!q.isBlank()){String v="%"+q.toLowerCase()+"%";x.add(b.or(b.like(b.lower(r.get("title")),v),b.like(b.lower(r.get("reference")),v),b.like(b.lower(r.get("location")),v)));}if(departmentId!=null)x.add(b.equal(r.get("department").get("id"),departmentId));if(a!=null&&managerOnly(a))x.add(b.equal(r.get("hiringManager").get("id"),employee(a).getId()));return b.and(x.toArray(Predicate[]::new));};return offers.findAll(s,p).map(this::offerView);}
 @Transactional(readOnly=true) public JobOfferView getOffer(Long id,Authentication a){JobOffer o=offer(id);ensureOffer(o,a);return offerView(o);}

 @Transactional public CandidateView createCandidate(CandidateInput i,String actor){if(candidates.findByEmailIgnoreCase(i.email()).isPresent())throw ApiException.conflict("Un candidat utilise déjà cet email");Candidate c=new Candidate();apply(c,i);c=candidates.save(c);audit("CANDIDATE",c.getId(),"CREATED",actor,null);return candidateView(c);}
 @Transactional public CandidateView updateCandidate(Long id,CandidateInput i,String actor){Candidate c=candidate(id);if(candidates.existsByEmailIgnoreCaseAndIdNot(i.email(),id))throw ApiException.conflict("Un candidat utilise déjà cet email");apply(c,i);audit("CANDIDATE",id,"UPDATED",actor,null);return candidateView(c);}
 @Transactional(readOnly=true) public Page<CandidateView> listCandidates(String q,Pageable p){Specification<Candidate>s=(r,c,b)->{if(q==null||q.isBlank())return b.conjunction();String v="%"+q.toLowerCase()+"%";return b.or(b.like(b.lower(r.get("firstName")),v),b.like(b.lower(r.get("lastName")),v),b.like(b.lower(r.get("email")),v),b.like(b.lower(r.get("city")),v));};return candidates.findAll(s,p).map(this::candidateView);}
 @Transactional(readOnly=true) public CandidateView getCandidate(Long id){return candidateView(candidate(id));}

 @Transactional public ApplicationView createApplication(ApplicationInput i,String actor){Candidate c=candidate(i.candidateId());JobOffer o=offer(i.jobOfferId());if(o.getStatus()!=JobOfferStatus.PUBLISHED||o.getClosingDate()!=null&&o.getClosingDate().isBefore(LocalDate.now()))throw ApiException.conflict("Cette offre n’accepte pas de candidatures");if(applications.existsByCandidateIdAndJobOfferId(c.getId(),o.getId()))throw ApiException.conflict("Une candidature existe déjà pour ce candidat et cette offre");Application a=new Application();a.setCandidate(c);a.setJobOffer(o);a.setSource(i.source().trim());a.setNotes(i.notes());a=applications.save(a);audit("APPLICATION",a.getId(),"CREATED",actor,null);metrics.counter("hrflow.recruitment.applications.created").increment();email.applicationReceived(c.getEmail(),o.getReference());return applicationView(a);}
 @Transactional(readOnly=true) public Page<ApplicationView> listApplications(Long offerId,ApplicationStage stage,ApplicationStatus status,Pageable p,Authentication auth){Specification<Application>s=(r,c,b)->{List<Predicate>x=new ArrayList<>();if(offerId!=null)x.add(b.equal(r.get("jobOffer").get("id"),offerId));if(stage!=null)x.add(b.equal(r.get("stage"),stage));if(status!=null)x.add(b.equal(r.get("status"),status));if(managerOnly(auth))x.add(b.equal(r.get("jobOffer").get("hiringManager").get("id"),employee(auth).getId()));return b.and(x.toArray(Predicate[]::new));};return applications.findAll(s,p).map(this::applicationView);}
 @Transactional(readOnly=true) public ApplicationView getApplication(Long id,Authentication auth){Application a=application(id);ensureApplication(a,auth);return applicationView(a);}
 @Transactional public ApplicationView transition(Long id,StageInput i,Authentication auth){Application a=application(id);ensureApplication(a,auth);if(i.stage()==ApplicationStage.REJECTED)throw ApiException.conflict("Utilisez l’action de rejet avec une justification");if(i.stage()==ApplicationStage.HIRED)return hire(id,auth);if(a.getStatus()!=ApplicationStatus.ACTIVE||!TRANSITIONS.getOrDefault(a.getStage(),Set.of()).contains(i.stage()))throw ApiException.conflict("Transition de pipeline interdite");ApplicationStage old=a.getStage();a.setStage(i.stage());audit("APPLICATION",id,"STAGE_CHANGED",auth.getName(),old+" -> "+i.stage());metrics.counter("hrflow.recruitment.transitions", "to",i.stage().name()).increment();return applicationView(a);}
 @Transactional public ApplicationView reject(Long id,RejectionInput i,Authentication auth){Application a=application(id);ensureApplication(a,auth);if(a.getStatus()!=ApplicationStatus.ACTIVE)throw ApiException.conflict("La candidature n’est plus active");a.setStage(ApplicationStage.REJECTED);a.setStatus(ApplicationStatus.REJECTED);a.setRejectionReason(i.reason().trim());audit("APPLICATION",id,"REJECTED",auth.getName(),null);metrics.counter("hrflow.recruitment.rejections").increment();email.decision(a.getCandidate().getEmail(),false,a.getJobOffer().getReference());return applicationView(a);}
 @Transactional public ApplicationView withdraw(Long id,String actor){Application a=application(id);if(a.getStatus()!=ApplicationStatus.ACTIVE)throw ApiException.conflict("La candidature n’est plus active");a.setStage(ApplicationStage.WITHDRAWN);a.setStatus(ApplicationStatus.WITHDRAWN);audit("APPLICATION",id,"WITHDRAWN",actor,null);return applicationView(a);}
 @Transactional public ApplicationView hire(Long id,Authentication auth){Application a=application(id);ensureApplication(a,auth);if(a.getStatus()==ApplicationStatus.HIRED)return applicationView(a);if(a.getStatus()!=ApplicationStatus.ACTIVE||a.getStage()!=ApplicationStage.OFFER)throw ApiException.conflict("La candidature doit être à l’étape OFFER");if(!interviews.existsByApplicationIdAndStatus(id,InterviewStatus.COMPLETED)||!evaluations.existsByInterviewApplicationIdAndRecommendationIn(id,List.of(Recommendation.HIRE,Recommendation.STRONG_HIRE)))throw ApiException.conflict("Un entretien terminé et une évaluation favorable sont requis");Candidate c=a.getCandidate();User u=users.findByEmailIgnoreCase(c.getEmail()).orElseGet(()->{User n=new User();n.setEmail(c.getEmail().toLowerCase());n.setPasswordHash(encoder.encode(UUID.randomUUID().toString()+UUID.randomUUID()));n.setRole(Role.EMPLOYEE);return users.save(n);});Employee e=employees.findByUserEmailIgnoreCase(c.getEmail()).orElseGet(()->{Employee n=new Employee();n.setEmployeeNumber("REC-"+String.format("%06d",a.getId()));n.setFirstName(c.getFirstName());n.setLastName(c.getLastName());n.setPhone(c.getPhone());n.setHireDate(LocalDate.now());n.setPosition(a.getJobOffer().getTitle());n.setDepartment(a.getJobOffer().getDepartment());n.setManager(a.getJobOffer().getHiringManager());n.setUser(u);return employees.save(n);});a.setHiredEmployee(e);a.setStage(ApplicationStage.HIRED);a.setStatus(ApplicationStatus.HIRED);audit("APPLICATION",id,"HIRED",auth.getName(),"employeeId="+e.getId());metrics.counter("hrflow.recruitment.hires").increment();email.decision(c.getEmail(),true,a.getJobOffer().getReference());autoClose(a.getJobOffer(),auth.getName());return applicationView(a);}

 @Transactional public InterviewView createInterview(InterviewInput i,Authentication auth){Application a=application(i.applicationId());ensureApplication(a,auth);if(a.getStatus()!=ApplicationStatus.ACTIVE)throw ApiException.conflict("Entretien réservé à une candidature active");Interview v=new Interview();apply(v,i);v.setApplication(a);v=interviews.save(v);audit("INTERVIEW",v.getId(),"SCHEDULED",auth.getName(),null);metrics.counter("hrflow.recruitment.interviews").increment();email.interview(a.getCandidate().getEmail(),"Convocation à un entretien","Un entretien est prévu le "+v.getScheduledAt()+" ("+v.getInterviewType()+").");return interviewView(v);}
 @Transactional public InterviewView updateInterview(Long id,InterviewInput i,Authentication auth){Interview v=interview(id);ensureInterview(v,auth);if(v.getStatus()!=InterviewStatus.SCHEDULED)throw ApiException.conflict("Seul un entretien planifié peut être modifié");if(!Objects.equals(v.getApplication().getId(),i.applicationId()))throw ApiException.conflict("La candidature d’un entretien ne peut pas changer");apply(v,i);audit("INTERVIEW",id,"UPDATED",auth.getName(),null);email.interview(v.getApplication().getCandidate().getEmail(),"Entretien modifié","Votre entretien est maintenant prévu le "+v.getScheduledAt()+".");return interviewView(v);}
 @Transactional public InterviewView interviewStatus(Long id,InterviewStatus status,Authentication auth){Interview v=interview(id);ensureInterview(v,auth);if(v.getStatus()!=InterviewStatus.SCHEDULED||status==InterviewStatus.SCHEDULED)throw ApiException.conflict("Changement de statut d’entretien interdit");v.setStatus(status);audit("INTERVIEW",id,status.name(),auth.getName(),null);if(status==InterviewStatus.CANCELLED)email.interview(v.getApplication().getCandidate().getEmail(),"Entretien annulé","Votre entretien a été annulé. Notre équipe vous recontactera.");return interviewView(v);}
 @Transactional(readOnly=true) public Page<InterviewView> listInterviews(Long applicationId,Instant from,Pageable p,Authentication auth){Specification<Interview>s=(r,c,b)->{List<Predicate>x=new ArrayList<>();if(applicationId!=null)x.add(b.equal(r.get("application").get("id"),applicationId));if(from!=null)x.add(b.greaterThanOrEqualTo(r.get("scheduledAt"),from));if(employeeOnly(auth))x.add(b.equal(r.get("interviewer").get("id"),employee(auth).getId()));else if(managerOnly(auth))x.add(b.equal(r.get("application").get("jobOffer").get("hiringManager").get("id"),employee(auth).getId()));return b.and(x.toArray(Predicate[]::new));};return interviews.findAll(s,p).map(this::interviewView);}
 @Transactional public EvaluationView saveEvaluation(Long id,EvaluationInput i,Authentication auth){Interview v=interview(i.interviewId());ensureInterview(v,auth);Employee evaluator=employees.findById(i.evaluatorId()).orElseThrow(()->ApiException.notFound("Évaluateur introuvable"));if(!adminHr(auth)&&!Objects.equals(evaluator.getUser()==null?null:evaluator.getUser().getEmail(),auth.getName()))throw new AccessDeniedException("Évaluation non autorisée");if(v.getStatus()!=InterviewStatus.COMPLETED)throw ApiException.conflict("L’entretien doit être terminé");Evaluation e=id==null?evaluations.findByInterviewId(i.interviewId()).orElse(new Evaluation()):evaluations.findById(id).orElseThrow(()->ApiException.notFound("Évaluation introuvable"));if(e.getId()!=null&&!Objects.equals(e.getEvaluator().getId(),evaluator.getId())&&!adminHr(auth))throw new AccessDeniedException("Évaluation non autorisée");e.setInterview(v);e.setEvaluator(evaluator);e.setTechnicalScore(i.technicalScore());e.setCommunicationScore(i.communicationScore());e.setCultureScore(i.cultureScore());e.setRecommendation(i.recommendation());e.setComments(i.comments());e=evaluations.save(e);audit("EVALUATION",e.getId(),id==null?"SAVED":"UPDATED",auth.getName(),null);return evaluationView(e);}
 @Transactional(readOnly=true) public EvaluationView getEvaluation(Long id,Authentication auth){Evaluation e=evaluations.findById(id).orElseThrow(()->ApiException.notFound("Évaluation introuvable"));ensureInterview(e.getInterview(),auth);return evaluationView(e);}
 @Transactional(readOnly=true) public RecruitmentDashboard dashboard(Authentication auth){if(managerOnly(auth)){throw new AccessDeniedException("Dashboard global réservé aux RH");}Map<ApplicationStage,Long> by=new EnumMap<>(ApplicationStage.class);for(ApplicationStage s:ApplicationStage.values())by.put(s,applications.countByStage(s));List<Application> hired=applications.findAll((r,c,b)->b.equal(r.get("status"),ApplicationStatus.HIRED));double avg=hired.stream().mapToLong(a->ChronoUnit.DAYS.between(a.getAppliedAt(),a.getUpdatedAt())).average().orElse(0);return new RecruitmentDashboard(offers.countByStatus(JobOfferStatus.PUBLISHED),applications.count(),by,applications.countByStatus(ApplicationStatus.HIRED),applications.countByStatus(ApplicationStatus.REJECTED),avg,interviews.countByStatusAndScheduledAtAfter(InterviewStatus.SCHEDULED,Instant.now()));}
 @Transactional(readOnly=true) public Page<AuditView> applicationAudit(Long id,Pageable p,Authentication auth){Application a=application(id);ensureApplication(a,auth);return auditRepo.findByEntityTypeAndEntityIdOrderByOccurredAtDesc("APPLICATION",id,p).map(x->new AuditView(x.getId(),x.getEntityType(),x.getEntityId(),x.getAction(),x.getActorEmail(),x.getDetails(),x.getOccurredAt()));}

 private void apply(JobOffer o,JobOfferInput i){Department d=departments.findById(i.departmentId()).orElseThrow(()->ApiException.notFound("Département introuvable"));if(!d.isActive())throw ApiException.conflict("Le département est inactif");Employee m=i.hiringManagerId()==null?null:employees.findById(i.hiringManagerId()).orElseThrow(()->ApiException.notFound("Manager introuvable"));o.setReference(i.reference().trim().toUpperCase());o.setTitle(i.title().trim());o.setDescription(i.description().trim());o.setRequirements(i.requirements().trim());o.setLocation(i.location().trim());o.setEmploymentType(i.employmentType());o.setDepartment(d);o.setHiringManager(m);o.setClosingDate(i.closingDate());}
 private void apply(Candidate c,CandidateInput i){c.setFirstName(i.firstName().trim());c.setLastName(i.lastName().trim());c.setEmail(i.email().trim().toLowerCase());c.setPhone(i.phone().trim());c.setCity(i.city().trim());c.setLinkedInUrl(i.linkedInUrl());c.setPortfolioUrl(i.portfolioUrl());}
 private void apply(Interview v,InterviewInput i){if(!i.scheduledAt().isAfter(Instant.now()))throw ApiException.conflict("La date d’entretien doit être future");v.setInterviewer(employees.findById(i.interviewerId()).orElseThrow(()->ApiException.notFound("Interviewer introuvable")));v.setScheduledAt(i.scheduledAt());v.setDurationMinutes(i.durationMinutes());v.setInterviewType(i.interviewType().trim());v.setLocationOrMeetingUrl(i.locationOrMeetingUrl().trim());v.setNotes(i.notes());}
 private void autoClose(JobOffer o,String actor){if(applications.findByJobOfferIdAndStatus(o.getId(),ApplicationStatus.ACTIVE).stream().noneMatch(x->x.getId()!=null)){o.setStatus(JobOfferStatus.CLOSED);audit("JOB_OFFER",o.getId(),"AUTO_CLOSED",actor,"Aucune candidature active après embauche");}}
 JobOffer offer(Long id){return offers.findById(id).orElseThrow(()->ApiException.notFound("Offre introuvable"));} Candidate candidate(Long id){return candidates.findById(id).orElseThrow(()->ApiException.notFound("Candidat introuvable"));} Application application(Long id){return applications.findById(id).orElseThrow(()->ApiException.notFound("Candidature introuvable"));} Interview interview(Long id){return interviews.findById(id).orElseThrow(()->ApiException.notFound("Entretien introuvable"));}
 private Employee employee(Authentication a){return employees.findByUserEmailIgnoreCase(a.getName()).orElseThrow(()->new AccessDeniedException("Profil employé requis"));} private boolean adminHr(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_HR"));}private boolean managerOnly(Authentication a){return a!=null&&!adminHr(a)&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_MANAGER"));}private boolean employeeOnly(Authentication a){return a!=null&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_EMPLOYEE"));}
 private void ensureOffer(JobOffer o,Authentication a){if(managerOnly(a)&&!Objects.equals(o.getHiringManager()==null?null:o.getHiringManager().getId(),employee(a).getId()))throw new AccessDeniedException("Offre non autorisée");}
 private void ensureApplication(Application x,Authentication a){ensureOffer(x.getJobOffer(),a);}
 private void ensureInterview(Interview v,Authentication a){if(employeeOnly(a)&&!Objects.equals(v.getInterviewer().getId(),employee(a).getId()))throw new AccessDeniedException("Entretien non autorisé");else ensureApplication(v.getApplication(),a);}
 private void audit(String type,Long id,String action,String actor,String details){RecruitmentAudit a=new RecruitmentAudit();a.setEntityType(type);a.setEntityId(id);a.setAction(action);a.setActorEmail(actor);a.setDetails(details);auditRepo.save(a);}
 JobOfferView offerView(JobOffer o){return new JobOfferView(o.getId(),o.getReference(),o.getTitle(),o.getDescription(),o.getRequirements(),o.getLocation(),o.getEmploymentType(),o.getStatus(),o.getDepartment().getId(),o.getDepartment().getName(),o.getHiringManager()==null?null:o.getHiringManager().getId(),o.getPublishedAt(),o.getClosingDate(),o.getCreatedAt(),o.getUpdatedAt());}
 CandidateView candidateView(Candidate c){return new CandidateView(c.getId(),c.getFirstName(),c.getLastName(),c.getEmail(),c.getPhone(),c.getCity(),c.getLinkedInUrl(),c.getPortfolioUrl(),c.getCreatedAt(),c.getUpdatedAt());}
 ApplicationView applicationView(Application a){return new ApplicationView(a.getId(),candidateView(a.getCandidate()),offerView(a.getJobOffer()),a.getStage(),a.getStatus(),a.getSource(),a.getAppliedAt(),a.getUpdatedAt(),a.getRejectionReason(),a.getNotes(),a.getHiredEmployee()==null?null:a.getHiredEmployee().getId());}
 InterviewView interviewView(Interview v){return new InterviewView(v.getId(),v.getApplication().getId(),v.getInterviewer().getId(),v.getInterviewer().getFirstName()+" "+v.getInterviewer().getLastName(),v.getScheduledAt(),v.getDurationMinutes(),v.getInterviewType(),v.getLocationOrMeetingUrl(),v.getStatus(),v.getNotes(),v.getCreatedAt(),v.getUpdatedAt());}
 EvaluationView evaluationView(Evaluation e){return new EvaluationView(e.getId(),e.getInterview().getId(),e.getEvaluator().getId(),e.getTechnicalScore(),e.getCommunicationScore(),e.getCultureScore(),e.getRecommendation(),e.getComments(),e.getCreatedAt());}
}
