package com.hrflow.platform.recruitment;
import com.hrflow.platform.recruitment.RecruitmentDtos.*; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.time.Instant;
@RestController @RequestMapping("/api/v1/recruitment") @RequiredArgsConstructor
public class RecruitmentController {private final RecruitmentService service;private final CvStorageService cvs;
 @GetMapping("/offers") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") Page<JobOfferView> offers(@RequestParam(required=false)String search,@RequestParam(required=false)JobOfferStatus status,@RequestParam(required=false)Long departmentId,@PageableDefault(sort="createdAt",direction=Sort.Direction.DESC)Pageable p,Authentication a){return service.listOffers(search,status,departmentId,p,a,false);}
 @GetMapping("/offers/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") JobOfferView offer(@PathVariable Long id,Authentication a){return service.getOffer(id,a);}
 @PostMapping("/offers") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('ADMIN','HR')") JobOfferView createOffer(@Valid @RequestBody JobOfferInput i,Authentication a){return service.createOffer(i,a.getName());}
 @PutMapping("/offers/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR')") JobOfferView updateOffer(@PathVariable Long id,@Valid @RequestBody JobOfferInput i,Authentication a){return service.updateOffer(id,i,a.getName());}
 @PatchMapping("/offers/{id}/publish") @PreAuthorize("hasAnyRole('ADMIN','HR')") JobOfferView publish(@PathVariable Long id,Authentication a){return service.publish(id,a.getName());}
 @PatchMapping("/offers/{id}/close") @PreAuthorize("hasAnyRole('ADMIN','HR')") JobOfferView close(@PathVariable Long id,Authentication a){return service.close(id,a.getName());}
 @PatchMapping("/offers/{id}/cancel") @PreAuthorize("hasAnyRole('ADMIN','HR')") JobOfferView cancel(@PathVariable Long id,Authentication a){return service.cancel(id,a.getName());}
 @GetMapping("/candidates") @PreAuthorize("hasAnyRole('ADMIN','HR')") Page<CandidateView> candidates(@RequestParam(required=false)String search,@PageableDefault(sort="lastName")Pageable p){return service.listCandidates(search,p);}
 @GetMapping("/candidates/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR')") CandidateView candidate(@PathVariable Long id){return service.getCandidate(id);}
 @PostMapping("/candidates") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('ADMIN','HR')") CandidateView createCandidate(@Valid @RequestBody CandidateInput i,Authentication a){return service.createCandidate(i,a.getName());}
 @PutMapping("/candidates/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR')") CandidateView updateCandidate(@PathVariable Long id,@Valid @RequestBody CandidateInput i,Authentication a){return service.updateCandidate(id,i,a.getName());}
 @GetMapping("/applications") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") Page<ApplicationView> applications(@RequestParam(required=false)Long offerId,@RequestParam(required=false)ApplicationStage stage,@RequestParam(required=false)ApplicationStatus status,@PageableDefault(sort="appliedAt",direction=Sort.Direction.DESC)Pageable p,Authentication a){return service.listApplications(offerId,stage,status,p,a);}
 @GetMapping("/applications/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") ApplicationView application(@PathVariable Long id,Authentication a){return service.getApplication(id,a);}
 @PostMapping("/applications") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('ADMIN','HR')") ApplicationView createApplication(@Valid @RequestBody ApplicationInput i,Authentication a){return service.createApplication(i,a.getName());}
 @PatchMapping("/applications/{id}/stage") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") ApplicationView stage(@PathVariable Long id,@Valid @RequestBody StageInput i,Authentication a){return service.transition(id,i,a);}
 @PatchMapping("/applications/{id}/reject") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") ApplicationView reject(@PathVariable Long id,@Valid @RequestBody RejectionInput i,Authentication a){return service.reject(id,i,a);}
 @PatchMapping("/applications/{id}/withdraw") @PreAuthorize("hasAnyRole('ADMIN','HR')") ApplicationView withdraw(@PathVariable Long id,Authentication a){return service.withdraw(id,a.getName());}
 @PostMapping("/applications/{id}/hire") @PreAuthorize("hasAnyRole('ADMIN','HR')") ApplicationView hire(@PathVariable Long id,Authentication a){return service.hire(id,a);}
 @GetMapping("/interviews") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER','EMPLOYEE')") Page<InterviewView> interviews(@RequestParam(required=false)Long applicationId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant from,@PageableDefault(sort="scheduledAt")Pageable p,Authentication a){return service.listInterviews(applicationId,from,p,a);}
 @PostMapping("/interviews") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") InterviewView createInterview(@Valid @RequestBody InterviewInput i,Authentication a){return service.createInterview(i,a);}
 @PutMapping("/interviews/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") InterviewView updateInterview(@PathVariable Long id,@Valid @RequestBody InterviewInput i,Authentication a){return service.updateInterview(id,i,a);}
 @PatchMapping("/interviews/{id}/cancel") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") InterviewView cancelInterview(@PathVariable Long id,Authentication a){return service.interviewStatus(id,InterviewStatus.CANCELLED,a);}
 @PatchMapping("/interviews/{id}/complete") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER','EMPLOYEE')") InterviewView completeInterview(@PathVariable Long id,Authentication a){return service.interviewStatus(id,InterviewStatus.COMPLETED,a);}
 @PostMapping("/evaluations") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER','EMPLOYEE')") EvaluationView evaluation(@Valid @RequestBody EvaluationInput i,Authentication a){return service.saveEvaluation(null,i,a);}
 @PutMapping("/evaluations/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER','EMPLOYEE')") EvaluationView updateEvaluation(@PathVariable Long id,@Valid @RequestBody EvaluationInput i,Authentication a){return service.saveEvaluation(id,i,a);}
 @GetMapping("/evaluations/{id}") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER','EMPLOYEE')") EvaluationView evaluation(@PathVariable Long id,Authentication a){return service.getEvaluation(id,a);}
 @PostMapping(path="/candidates/{id}/cv",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAnyRole('ADMIN','HR')") CvView upload(@PathVariable Long id,@RequestPart("file")MultipartFile file){return cvs.store(id,file);}
 @GetMapping("/candidates/{id}/cv/metadata") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") CvView metadata(@PathVariable Long id){return cvs.metadata(id);}
 @GetMapping("/candidates/{id}/cv") @PreAuthorize("hasAnyRole('ADMIN','HR','MANAGER')") ResponseEntity<org.springframework.core.io.Resource> download(@PathVariable Long id){var d=cvs.download(id);return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(d.metadata().originalFilename()).build().toString()).contentLength(d.metadata().size()).body(d.resource());}
 @DeleteMapping("/candidates/{id}/cv") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAnyRole('ADMIN','HR')") void deleteCv(@PathVariable Long id){cvs.delete(id);}
 @GetMapping("/dashboard") @PreAuthorize("hasAnyRole('ADMIN','HR')") RecruitmentDashboard dashboard(Authentication a){return service.dashboard(a);}
}
