package com.hrflow.platform.security;
import com.fasterxml.jackson.databind.ObjectMapper; import jakarta.servlet.http.HttpServletResponse; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.MediaType; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.*; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.cors.*; import java.time.Instant; import java.util.*;
import com.hrflow.platform.user.UserRepository; import org.springframework.security.core.userdetails.UserDetailsService;
@Configuration @EnableMethodSecurity @RequiredArgsConstructor
public class SecurityConfig { private final JwtAuthenticationFilter jwt;
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder(12);}
 @Bean UserDetailsService userDetailsService(UserRepository users){return email->{var u=users.findByEmailIgnoreCase(email).orElseThrow(()->new org.springframework.security.core.userdetails.UsernameNotFoundException("Utilisateur introuvable"));return org.springframework.security.core.userdetails.User.withUsername(u.getEmail()).password(u.getPasswordHash()).disabled(!u.isEnabled()).authorities("ROLE_"+u.getRole().name()).build();};}
 @Bean CorsConfigurationSource cors(@Value("${hrflow.cors.allowed-origins:http://localhost:4200}")List<String> origins){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(origins);c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","OPTIONS"));c.setAllowedHeaders(List.of("Authorization","Content-Type","X-Correlation-ID"));c.setExposedHeaders(List.of("X-Correlation-ID"));UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
 @Bean SecurityFilterChain chain(HttpSecurity h,ObjectMapper mapper)throws Exception {return h.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a
  .requestMatchers("/api/v1/auth/register","/api/v1/auth/login","/api/v1/auth/verify-email","/api/v1/auth/resend-verification","/api/v1/auth/forgot-password","/api/v1/auth/reset-password").permitAll()
  .requestMatchers("/actuator/health","/actuator/info","/v3/api-docs/**","/swagger-ui/**","/swagger-ui.html").permitAll().requestMatchers("/actuator/**").hasRole("ADMIN").anyRequest().authenticated())
  .exceptionHandling(e->e.authenticationEntryPoint((q,r,x)->json(mapper,r,401,"AUTHENTICATION_REQUIRED","Authentification requise",q.getRequestURI())).accessDeniedHandler((q,r,x)->json(mapper,r,403,"ACCESS_DENIED","Accès interdit",q.getRequestURI())))
  .addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).build();}
 private static void json(ObjectMapper m,HttpServletResponse r,int status,String code,String message,String path)throws java.io.IOException{r.setStatus(status);r.setContentType(MediaType.APPLICATION_JSON_VALUE);m.writeValue(r.getOutputStream(),Map.of("timestamp",Instant.now(),"status",status,"error",status==401?"Unauthorized":"Forbidden","code",code,"message",message,"path",path));}
}
