package com.hrflow.platform.employee;
import com.hrflow.platform.common.ApiModels.*; import com.hrflow.platform.department.*; import com.hrflow.platform.exception.ApiException; import com.hrflow.platform.user.*; import jakarta.persistence.criteria.Predicate; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class EmployeeService {private final EmployeeRepository repo;private final DepartmentService departments;private final UserRepository users;
 @Transactional public EmployeeView create(EmployeeInput in){if(repo.existsByEmployeeNumberIgnoreCase(in.employeeNumber()))throw ApiException.conflict("Ce matricule existe déjà");Employee e=new Employee();apply(e,in);return view(repo.save(e));}
 @Transactional(readOnly=true) public Page<EmployeeView> list(String q,Long departmentId,Boolean active,Pageable p){Specification<Employee>s=(root,c,b)->{List<Predicate>x=new ArrayList<>();if(q!=null&&!q.isBlank()){String v="%"+q.toLowerCase()+"%";x.add(b.or(b.like(b.lower(root.get("firstName")),v),b.like(b.lower(root.get("lastName")),v),b.like(b.lower(root.get("employeeNumber")),v),b.like(b.lower(root.join("user",jakarta.persistence.criteria.JoinType.LEFT).get("email")),v)));}if(departmentId!=null)x.add(b.equal(root.get("department").get("id"),departmentId));if(active!=null)x.add(b.equal(root.get("active"),active));return b.and(x.toArray(Predicate[]::new));};return repo.findAll(s,p).map(this::view);}
 @Transactional(readOnly=true) public EmployeeView get(Long id,Authentication a){Employee e=entity(id);ensureVisible(e,a);return view(e);}@Transactional(readOnly=true) public EmployeeView me(String email){return view(byEmail(email));}
 @Transactional public EmployeeView update(Long id,EmployeeInput in){Employee e=entity(id);if(repo.existsByEmployeeNumberIgnoreCaseAndIdNot(in.employeeNumber(),id))throw ApiException.conflict("Ce matricule existe déjà");apply(e,in);return view(e);}@Transactional public EmployeeView status(Long id,StatusUpdate in){Employee e=entity(id);e.setActive(in.active());return view(e);}
 @Transactional(readOnly=true) public Page<EmployeeView> team(Long id,Authentication a,Pageable p){Employee manager=entity(id);if(!adminOrHr(a)&&!Objects.equals(byEmail(a.getName()).getId(),id))throw new AccessDeniedException("Équipe non autorisée");return repo.findByManagerId(manager.getId(),p).map(this::view);}
 public Employee byEmail(String email){return repo.findByUserEmailIgnoreCase(email).orElseThrow(()->ApiException.notFound("Aucun profil employé associé"));} public Employee entity(Long id){return repo.findById(id).orElseThrow(()->ApiException.notFound("Employé introuvable"));}
 private void apply(Employee e,EmployeeInput i){Department d=departments.entity(i.departmentId());if(!d.isActive())throw ApiException.conflict("Le département est inactif");Employee manager=i.managerId()==null?null:entity(i.managerId());if(e.getId()!=null&&Objects.equals(e.getId(),i.managerId()))throw ApiException.conflict("Un employé ne peut pas être son propre manager");User user=i.userId()==null?null:users.findById(i.userId()).orElseThrow(()->ApiException.notFound("Utilisateur introuvable"));e.setEmployeeNumber(i.employeeNumber().trim());e.setFirstName(i.firstName().trim());e.setLastName(i.lastName().trim());e.setPhone(i.phone());e.setHireDate(i.hireDate());e.setPosition(i.position().trim());e.setDepartment(d);e.setManager(manager);e.setUser(user);}
 private boolean adminOrHr(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_HR"));}private void ensureVisible(Employee e,Authentication a){if(adminOrHr(a))return;Employee self=byEmail(a.getName());if(Objects.equals(self.getId(),e.getId())||e.getManager()!=null&&Objects.equals(e.getManager().getId(),self.getId()))return;throw new AccessDeniedException("Employé non autorisé");}
 public EmployeeView view(Employee e){return new EmployeeView(e.getId(),e.getEmployeeNumber(),e.getFirstName(),e.getLastName(),e.getPhone(),e.getHireDate(),e.getPosition(),e.isActive(),e.getUser()==null?null:e.getUser().getId(),e.getUser()==null?null:e.getUser().getEmail(),e.getDepartment().getId(),e.getDepartment().getName(),e.getManager()==null?null:e.getManager().getId(),e.getCreatedAt(),e.getUpdatedAt());}
}
