import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';
import { ApiError, Application, ApplicationStage, Candidate, Department, Employee, Interview, JobOffer, RecruitmentDashboard } from '../../core/models/api.models';
import { ApiService } from '../../core/services/api.service';
import { NotificationService } from '../../core/services/notification.service';

@Component({selector:'app-recruitment',imports:[ReactiveFormsModule,RouterLink],template:`
<header class="page-head"><div><p class="eyebrow">Recrutement</p><h1>{{title()}}</h1><p class="muted">Pilotage sécurisé du recrutement, de l’offre à l’embauche.</p></div>
<nav class="actions" aria-label="Sections recrutement">@if(!employeeOnly()){<a class="button secondary" routerLink="/app/recrutement/dashboard">Dashboard</a><a class="button secondary" routerLink="/app/recrutement/offres">Offres</a><a class="button secondary" routerLink="/app/recrutement/candidats">Candidats</a><a class="button secondary" routerLink="/app/recrutement/pipeline">Pipeline</a>}<a class="button secondary" routerLink="/app/recrutement/entretiens">Entretiens</a></nav></header>
@if(loading()){<div class="state" role="status">Chargement…</div>}@else if(error()){<div class="state error" role="alert">{{error()}}</div>}
@if(mode==='dashboard'&&dashboard();as d){<section class="stats"><article><span>Offres actives</span><strong>{{d.activeOffers}}</strong></article><article><span>Candidatures</span><strong>{{d.totalApplications}}</strong></article><article><span>Recrutements</span><strong>{{d.hires}}</strong></article><article><span>Rejets</span><strong>{{d.rejections}}</strong></article></section><section class="grid"><article class="panel"><h2>Pipeline</h2>@for(s of stages;track s){<p class="row"><span>{{label(s)}}</span><strong>{{d.applicationsByStage[s]||0}}</strong></p>}</article><article class="panel"><h2>Indicateurs</h2><p>Délai moyen : <strong>{{d.averageHiringDays}} jours</strong></p><p>Entretiens à venir : <strong>{{d.upcomingInterviews}}</strong></p></article></section>}
@if(mode==='offers'){@if(canManage()){<button (click)="offerFormVisible.set(!offerFormVisible())">Nouvelle offre</button>}@if(offerFormVisible()){<form class="panel form-grid" [formGroup]="offerForm" (ngSubmit)="saveOffer()"><h2>Créer une offre</h2><label>Référence<input formControlName="reference"></label><label>Intitulé<input formControlName="title"></label><label>Lieu<input formControlName="location"></label><label>Contrat<select formControlName="employmentType"><option value="PERMANENT">CDI</option><option value="FIXED_TERM">CDD</option><option value="INTERNSHIP">Stage</option><option value="FREELANCE">Freelance</option></select></label><label>Département<select formControlName="departmentId"><option [ngValue]="null">Sélectionner</option>@for(d of departments();track d.id){<option [ngValue]="d.id">{{d.name}}</option>}</select></label><label>Date de clôture<input type="date" formControlName="closingDate"></label><label class="wide">Description<textarea formControlName="description"></textarea></label><label class="wide">Prérequis<textarea formControlName="requirements"></textarea></label><button [disabled]="offerForm.invalid">Enregistrer</button></form>}<div class="cards">@for(o of offers();track o.id){<article class="panel"><span class="badge" [class.off]="o.status!=='PUBLISHED'">{{o.status}}</span><h2>{{o.reference}} · {{o.title}}</h2><p>{{o.location}} · {{o.departmentName}}</p><p class="muted">{{o.employmentType}} · clôture {{o.closingDate||'non définie'}}</p>@if(canManage()){<div class="actions">@if(o.status==='DRAFT'){<button (click)="offerAction(o,'publish')">Publier</button>}@if(o.status==='PUBLISHED'){<button class="secondary" (click)="offerAction(o,'close')">Clôturer</button>}@if(o.status==='DRAFT'||o.status==='PUBLISHED'){<button class="danger" (click)="offerAction(o,'cancel')">Annuler</button>}</div>}</article>}@empty{<div class="state">Aucune offre.</div>}</div>}
@if(mode==='candidates'){<form class="panel form-grid" [formGroup]="candidateForm" (ngSubmit)="saveCandidate()"><h2>Nouveau candidat</h2><label>Prénom<input formControlName="firstName"></label><label>Nom<input formControlName="lastName"></label><label>Email<input type="email" formControlName="email"></label><label>Téléphone<input formControlName="phone"></label><label>Ville<input formControlName="city"></label><label>LinkedIn<input type="url" formControlName="linkedInUrl"></label><button [disabled]="candidateForm.invalid">Enregistrer</button></form><div class="table-wrap"><table><thead><tr><th>Candidat</th><th>Contact</th><th>Ville</th><th>CV</th></tr></thead><tbody>@for(c of candidates();track c.id){<tr><td>{{c.firstName}} {{c.lastName}}</td><td>{{c.email}}<small>{{c.phone}}</small></td><td>{{c.city}}</td><td><label class="button secondary">Charger PDF<input class="visually-hidden" type="file" accept="application/pdf" (change)="upload(c,$event)"></label><button class="secondary" (click)="download(c)">Télécharger</button></td></tr>}</tbody></table></div>}
@if(mode==='applications'){<form class="toolbar" [formGroup]="applicationForm" (ngSubmit)="createApplication()"><label>Candidat<select formControlName="candidateId"><option [ngValue]="null">Sélectionner</option>@for(c of candidates();track c.id){<option [ngValue]="c.id">{{c.firstName}} {{c.lastName}}</option>}</select></label><label>Offre<select formControlName="jobOfferId"><option [ngValue]="null">Sélectionner</option>@for(o of offers();track o.id){<option [ngValue]="o.id">{{o.reference}} · {{o.title}}</option>}</select></label><label>Source<input formControlName="source"></label><button [disabled]="applicationForm.invalid">Créer</button></form>{{applicationTable()}}
<div class="table-wrap"><table><thead><tr><th>Candidat</th><th>Offre</th><th>Étape</th><th>Décision</th></tr></thead><tbody>@for(a of applications();track a.id){<tr><td>{{a.candidate.firstName}} {{a.candidate.lastName}}</td><td>{{a.jobOffer.reference}}</td><td>{{label(a.stage)}}</td><td>@if(a.status==='ACTIVE'){<button class="danger" (click)="reject(a)">Rejeter</button>@if(a.stage==='OFFER'&&canManage()){<button (click)="hire(a)">Embaucher</button>}}</td></tr>}</tbody></table></div>}
@if(mode==='pipeline'){<p class="muted">Sélectionnez une nouvelle étape. En cas de conflit 409, la carte reste dans sa colonne initiale.</p><div class="kanban">@for(s of activeStages;track s){<section class="panel" [attr.aria-label]="label(s)"><h2>{{label(s)}}</h2>@for(a of atStage(s);track a.id){<article class="kanban-card" tabindex="0"><strong>{{a.candidate.firstName}} {{a.candidate.lastName}}</strong><small>{{a.jobOffer.reference}}</small><label>Déplacer vers<select [value]="a.stage" (change)="move(a,$event)">@for(n of allowed(a.stage);track n){<option [value]="n">{{label(n)}}</option>}</select></label></article>}</section>}</div>}
@if(mode==='interviews'){ @if(!employeeOnly()){<form class="panel form-grid" [formGroup]="interviewForm" (ngSubmit)="saveInterview()"><h2>Planifier un entretien</h2><label>Candidature<select formControlName="applicationId"><option [ngValue]="null">Sélectionner</option>@for(a of applications();track a.id){<option [ngValue]="a.id">{{a.candidate.firstName}} {{a.candidate.lastName}}</option>}</select></label><label>Interviewer<select formControlName="interviewerId"><option [ngValue]="null">Sélectionner</option>@for(e of employees();track e.id){<option [ngValue]="e.id">{{e.firstName}} {{e.lastName}}</option>}</select></label><label>Date et heure<input type="datetime-local" formControlName="scheduledAt"></label><label>Durée<input type="number" min="15" max="480" formControlName="durationMinutes"></label><label>Type<input formControlName="interviewType"></label><label>Lieu ou lien<input formControlName="locationOrMeetingUrl"></label><button [disabled]="interviewForm.invalid">Planifier</button></form>}<div class="cards">@for(i of interviews();track i.id){<article class="panel"><span class="badge">{{i.status}}</span><h2>{{i.interviewType}}</h2><p>{{i.scheduledAt}} · {{i.durationMinutes}} min</p><p>{{i.interviewerName}} · {{i.locationOrMeetingUrl}}</p>@if(i.status==='SCHEDULED'){<button (click)="interviewAction(i,'complete')">Finaliser</button>@if(!employeeOnly()){<button class="danger" (click)="interviewAction(i,'cancel')">Annuler</button>}}</article>}@empty{<div class="state">Aucun entretien.</div>}</div>}
@if(mode==='evaluations'){<form class="panel form-grid" [formGroup]="evaluationForm" (ngSubmit)="saveEvaluation()"><h2>Évaluation</h2><label>Entretien<select formControlName="interviewId"><option [ngValue]="null">Sélectionner</option>@for(i of completedInterviews();track i.id){<option [ngValue]="i.id">#{{i.id}} · {{i.interviewType}}</option>}</select></label><label>Évaluateur<select formControlName="evaluatorId"><option [ngValue]="null">Sélectionner</option>@for(e of employees();track e.id){<option [ngValue]="e.id">{{e.firstName}} {{e.lastName}}</option>}</select></label><label>Technique (1–5)<input type="number" min="1" max="5" formControlName="technicalScore"></label><label>Communication (1–5)<input type="number" min="1" max="5" formControlName="communicationScore"></label><label>Culture (1–5)<input type="number" min="1" max="5" formControlName="cultureScore"></label><label>Recommandation<select formControlName="recommendation"><option value="STRONG_HIRE">Très favorable</option><option value="HIRE">Favorable</option><option value="NO_HIRE">Défavorable</option><option value="STRONG_NO_HIRE">Très défavorable</option></select></label><label class="wide">Commentaires<textarea formControlName="comments"></textarea></label><button [disabled]="evaluationForm.invalid">Enregistrer</button></form>}
`})
export class RecruitmentPage{
 private api=inject(ApiService);private notices=inject(NotificationService);readonly auth=inject(AuthService);mode=inject(ActivatedRoute).snapshot.data['mode'] as string;
 readonly loading=signal(true);readonly error=signal('');readonly dashboard=signal<RecruitmentDashboard|null>(null);readonly offers=signal<JobOffer[]>([]);readonly candidates=signal<Candidate[]>([]);readonly applications=signal<Application[]>([]);readonly interviews=signal<Interview[]>([]);readonly departments=signal<Department[]>([]);readonly employees=signal<Employee[]>([]);readonly offerFormVisible=signal(false);
 readonly stages:ApplicationStage[]=['APPLIED','SCREENING','INTERVIEW','TECHNICAL_TEST','HR_INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN'];readonly activeStages:ApplicationStage[]=['APPLIED','SCREENING','INTERVIEW','TECHNICAL_TEST','HR_INTERVIEW','OFFER'];
 readonly offerForm=new FormGroup({reference:new FormControl('',{nonNullable:true,validators:[Validators.required]}),title:new FormControl('',{nonNullable:true,validators:[Validators.required]}),description:new FormControl('',{nonNullable:true,validators:[Validators.required]}),requirements:new FormControl('',{nonNullable:true,validators:[Validators.required]}),location:new FormControl('',{nonNullable:true,validators:[Validators.required]}),employmentType:new FormControl<'PERMANENT'|'FIXED_TERM'|'INTERNSHIP'|'FREELANCE'>('PERMANENT',{nonNullable:true}),departmentId:new FormControl<number|null>(null,Validators.required),hiringManagerId:new FormControl<number|null>(null),closingDate:new FormControl<string|null>(null)});
 readonly candidateForm=new FormGroup({firstName:new FormControl('',{nonNullable:true,validators:[Validators.required]}),lastName:new FormControl('',{nonNullable:true,validators:[Validators.required]}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),phone:new FormControl('',{nonNullable:true,validators:[Validators.required]}),city:new FormControl('',{nonNullable:true,validators:[Validators.required]}),linkedInUrl:new FormControl<string|null>(null),portfolioUrl:new FormControl<string|null>(null)});
 readonly applicationForm=new FormGroup({candidateId:new FormControl<number|null>(null,Validators.required),jobOfferId:new FormControl<number|null>(null,Validators.required),source:new FormControl('DIRECT',{nonNullable:true,validators:[Validators.required]}),notes:new FormControl<string|null>(null)});
 readonly interviewForm=new FormGroup({applicationId:new FormControl<number|null>(null,Validators.required),interviewerId:new FormControl<number|null>(null,Validators.required),scheduledAt:new FormControl('',{nonNullable:true,validators:[Validators.required]}),durationMinutes:new FormControl(60,{nonNullable:true,validators:[Validators.min(15),Validators.max(480)]}),interviewType:new FormControl('Visioconférence',{nonNullable:true,validators:[Validators.required]}),locationOrMeetingUrl:new FormControl('',{nonNullable:true,validators:[Validators.required]}),notes:new FormControl<string|null>(null)});
 readonly evaluationForm=new FormGroup({interviewId:new FormControl<number|null>(null,Validators.required),evaluatorId:new FormControl<number|null>(null,Validators.required),technicalScore:new FormControl(3,{nonNullable:true,validators:[Validators.min(1),Validators.max(5)]}),communicationScore:new FormControl(3,{nonNullable:true,validators:[Validators.min(1),Validators.max(5)]}),cultureScore:new FormControl(3,{nonNullable:true,validators:[Validators.min(1),Validators.max(5)]}),recommendation:new FormControl<'STRONG_HIRE'|'HIRE'|'NO_HIRE'|'STRONG_NO_HIRE'>('HIRE',{nonNullable:true}),comments:new FormControl<string|null>(null)});
 constructor(){this.reload();if(inject(ActivatedRoute).snapshot.data['create'])this.offerFormVisible.set(true);}
 title(){return ({dashboard:'Dashboard recrutement',offers:'Offres d’emploi',candidates:'Candidats',applications:'Candidatures',pipeline:'Pipeline Kanban',interviews:'Entretiens',evaluations:'Évaluations'} as Record<string,string>)[this.mode]||'Recrutement';} canManage(){return ['ADMIN','HR'].includes(this.auth.user()?.role||'');} employeeOnly(){return this.auth.user()?.role==='EMPLOYEE';}
 reload(){this.loading.set(true);this.error.set('');const done=()=>this.loading.set(false);if(this.mode==='dashboard')this.api.recruitmentDashboard().subscribe({next:x=>{this.dashboard.set(x);done();},error:e=>this.fail(e)});else if(this.mode==='offers')this.api.jobOffers({size:100}).subscribe({next:x=>{this.offers.set(x.content);this.api.departments({size:100}).subscribe(y=>this.departments.set(y.content));done();},error:e=>this.fail(e)});else if(this.mode==='candidates')this.api.candidates({size:100}).subscribe({next:x=>{this.candidates.set(x.content);done();},error:e=>this.fail(e)});else if(['applications','pipeline'].includes(this.mode)){this.loadOptions();this.api.applications({size:200}).subscribe({next:x=>{this.applications.set(x.content);done();},error:e=>this.fail(e)});}else {this.loadOptions();this.api.interviews({size:100}).subscribe({next:x=>{this.interviews.set(x.content);done();},error:e=>this.fail(e)});}}
 loadOptions(){if(!this.employeeOnly()){this.api.candidates({size:200}).subscribe(x=>this.candidates.set(x.content));this.api.jobOffers({size:200}).subscribe(x=>this.offers.set(x.content));this.api.applications({status:'ACTIVE',size:200}).subscribe(x=>this.applications.set(x.content));this.api.employees({size:200,active:true}).subscribe(x=>this.employees.set(x.content));}}
 fail(e:ApiError){this.loading.set(false);this.error.set(e.message||'Une erreur est survenue.');} label(s:ApplicationStage){return s.replaceAll('_',' ');} applicationTable(){return '';}
 saveOffer(){if(this.offerForm.invalid)return;const v=this.offerForm.getRawValue();this.api.saveJobOffer({...v,departmentId:v.departmentId!}).subscribe({next:()=>{this.notices.show('Offre créée.','success');this.offerFormVisible.set(false);this.reload();},error:e=>this.fail(e)});}
 offerAction(o:JobOffer,a:'publish'|'close'|'cancel'){if(confirm(`Confirmer l’action ${a} ?`))this.api.offerAction(o.id,a).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});}
 saveCandidate(){if(this.candidateForm.invalid)return;this.api.saveCandidate(this.candidateForm.getRawValue()).subscribe({next:()=>{this.notices.show('Candidat enregistré.','success');this.candidateForm.reset();this.reload();},error:e=>this.fail(e)});}
 createApplication(){if(this.applicationForm.invalid)return;const v=this.applicationForm.getRawValue();this.api.createApplication({...v,candidateId:v.candidateId!,jobOfferId:v.jobOfferId!}).subscribe({next:()=>{this.notices.show('Candidature créée.','success');this.reload();},error:e=>this.fail(e)});}
 allowed(s:ApplicationStage):ApplicationStage[]{const map:Partial<Record<ApplicationStage,ApplicationStage[]>>={APPLIED:['APPLIED','SCREENING'],SCREENING:['SCREENING','INTERVIEW','TECHNICAL_TEST'],INTERVIEW:['INTERVIEW','TECHNICAL_TEST','HR_INTERVIEW'],TECHNICAL_TEST:['TECHNICAL_TEST','HR_INTERVIEW'],HR_INTERVIEW:['HR_INTERVIEW','OFFER'],OFFER:['OFFER']};return map[s]||[s];}atStage(s:ApplicationStage){return this.applications().filter(a=>a.stage===s);}
 move(a:Application,event:Event){const select=event.target as HTMLSelectElement;const previous=a.stage;const next=select.value as ApplicationStage;if(next===previous)return;this.api.transitionApplication(a.id,next).subscribe({next:x=>this.applications.update(rows=>rows.map(r=>r.id===x.id?x:r)),error:(e:ApiError)=>{select.value=previous;this.notices.show(e.message,'error');}});}
 reject(a:Application){const reason=prompt('Justification du rejet :')?.trim();if(reason)this.api.rejectApplication(a.id,reason).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});}hire(a:Application){if(confirm('Convertir ce candidat en employé ?'))this.api.hireApplication(a.id).subscribe({next:()=>{this.notices.show('Candidat embauché.','success');this.reload();},error:e=>this.fail(e)});}
 saveInterview(){if(this.interviewForm.invalid)return;const v=this.interviewForm.getRawValue();this.api.saveInterview({...v,applicationId:v.applicationId!,interviewerId:v.interviewerId!,scheduledAt:new Date(v.scheduledAt).toISOString()}).subscribe({next:()=>{this.notices.show('Entretien planifié.','success');this.reload();},error:e=>this.fail(e)});}interviewAction(i:Interview,a:'cancel'|'complete'){this.api.interviewAction(i.id,a).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});}
 completedInterviews(){return this.interviews().filter(i=>i.status==='COMPLETED');}saveEvaluation(){if(this.evaluationForm.invalid)return;const v=this.evaluationForm.getRawValue();this.api.saveEvaluation({...v,interviewId:v.interviewId!,evaluatorId:v.evaluatorId!}).subscribe({next:()=>this.notices.show('Évaluation enregistrée.','success'),error:e=>this.fail(e)});}
 upload(c:Candidate,event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)this.api.uploadCv(c.id,file).subscribe({next:()=>this.notices.show('CV chargé.','success'),error:e=>this.fail(e)});}download(c:Candidate){this.api.downloadCv(c.id).subscribe({next:b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`CV-${c.firstName}-${c.lastName}.pdf`;a.click();URL.revokeObjectURL(u);},error:e=>this.fail(e)});}
}
