package com.hrflow.platform.leave;
import com.hrflow.platform.common.ApiModels.*; import com.hrflow.platform.employee.*; import com.hrflow.platform.exception.ApiException; import com.hrflow.platform.user.*; import jakarta.persistence.criteria.Predicate; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class LeaveService {private final LeaveRequestRepository repo;private final EmployeeService employees;private final UserRepository users;
 @Transactional public LeaveView create(LeaveInput in,String email){if(in.startDate().isAfter(in.endDate()))throw ApiException.conflict("La date de début doit précéder la date de fin");Employee e=employees.byEmail(email);if(!e.isActive())throw ApiException.conflict("Le profil employé est inactif");if(repo.overlaps(e.getId(),in.startDate(),in.endDate(),List.of(LeaveStatus.PENDING,LeaveStatus.APPROVED)))throw ApiException.conflict("Une demande de congé chevauche cette période");LeaveRequest l=new LeaveRequest();l.setEmployee(e);l.setStartDate(in.startDate());l.setEndDate(in.endDate());l.setLeaveType(in.leaveType());l.setReason(in.reason());return view(repo.save(l));}
 @Transactional(readOnly=true) public Page<LeaveView> mine(String email,Pageable p){Long id=employees.byEmail(email).getId();return search(null,id,null,null,null,null,p).map(this::view);}
 @Transactional(readOnly=true) public Page<LeaveView> list(LeaveStatus status,Long employeeId,Long departmentId,LocalDate from,LocalDate to,Authentication a,Pageable p){Long managerId=isManagerOnly(a)?employees.byEmail(a.getName()).getId():null;return search(status,employeeId,departmentId,from,to,managerId,p).map(this::view);}
 private Page<LeaveRequest> search(LeaveStatus status,Long employeeId,Long departmentId,LocalDate from,LocalDate to,Long managerId,Pageable p){Specification<LeaveRequest>s=(root,c,b)->{List<Predicate>x=new ArrayList<>();if(status!=null)x.add(b.equal(root.get("status"),status));if(employeeId!=null)x.add(b.equal(root.get("employee").get("id"),employeeId));if(departmentId!=null)x.add(b.equal(root.get("employee").get("department").get("id"),departmentId));if(from!=null)x.add(b.greaterThanOrEqualTo(root.get("endDate"),from));if(to!=null)x.add(b.lessThanOrEqualTo(root.get("startDate"),to));if(managerId!=null)x.add(b.equal(root.get("employee").get("manager").get("id"),managerId));return b.and(x.toArray(Predicate[]::new));};return repo.findAll(s,p);}
 @Transactional(readOnly=true) public LeaveView get(Long id,Authentication a){LeaveRequest l=entity(id);ensureVisible(l,a);return view(l);}
 @Transactional public LeaveView approve(Long id,Decision d,Authentication a){return decide(id,d,a,LeaveStatus.APPROVED);}@Transactional public LeaveView reject(Long id,Decision d,Authentication a){if(d.managerComment()==null||d.managerComment().isBlank())throw ApiException.conflict("Un commentaire est obligatoire lors d'un rejet");return decide(id,d,a,LeaveStatus.REJECTED);}
 private LeaveView decide(Long id,Decision d,Authentication a,LeaveStatus status){LeaveRequest l=entity(id);if(l.getStatus()!=LeaveStatus.PENDING)throw ApiException.conflict("Seule une demande en attente peut être traitée");ensureReviewer(l,a);l.setStatus(status);l.setManagerComment(d.managerComment());l.setReviewedAt(Instant.now());l.setReviewedBy(users.findByEmailIgnoreCase(a.getName()).orElseThrow());return view(l);}
 @Transactional public LeaveView cancel(Long id,String email){LeaveRequest l=entity(id);if(!l.getEmployee().getUser().getEmail().equalsIgnoreCase(email))throw new AccessDeniedException("Demande non autorisée");if(l.getStatus()!=LeaveStatus.PENDING||!l.getStartDate().isAfter(LocalDate.now(ZoneOffset.UTC)))throw ApiException.conflict("Seule une demande future en attente peut être annulée");l.setStatus(LeaveStatus.CANCELLED);return view(l);}
 private void ensureReviewer(LeaveRequest l,Authentication a){if(has(a,"ROLE_ADMIN")||has(a,"ROLE_HR"))return;Employee self=employees.byEmail(a.getName());if(l.getEmployee().getManager()!=null&&Objects.equals(l.getEmployee().getManager().getId(),self.getId()))return;throw new AccessDeniedException("Demande hors équipe");}private void ensureVisible(LeaveRequest l,Authentication a){if(has(a,"ROLE_ADMIN")||has(a,"ROLE_HR"))return;Employee self=employees.byEmail(a.getName());if(Objects.equals(l.getEmployee().getId(),self.getId())||l.getEmployee().getManager()!=null&&Objects.equals(l.getEmployee().getManager().getId(),self.getId()))return;throw new AccessDeniedException("Demande non autorisée");}private boolean isManagerOnly(Authentication a){return has(a,"ROLE_MANAGER")&&!has(a,"ROLE_ADMIN")&&!has(a,"ROLE_HR");}private boolean has(Authentication a,String r){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals(r));}private LeaveRequest entity(Long id){return repo.findById(id).orElseThrow(()->ApiException.notFound("Demande introuvable"));}
 public LeaveView view(LeaveRequest l){Employee e=l.getEmployee();return new LeaveView(l.getId(),e.getId(),e.getFirstName()+" "+e.getLastName(),l.getStartDate(),l.getEndDate(),l.getLeaveType(),l.getReason(),l.getStatus(),l.getManagerComment(),l.getReviewedBy()==null?null:l.getReviewedBy().getId(),l.getReviewedAt(),l.getCreatedAt(),l.getUpdatedAt());}
}
